### ISSUE TITLE
https://wikiszotar.hu

### ISSUE THREAD

**Issue by benedek20** [hufilter/hufilter#1]
A WikiSzótáron a Szcientológia egyik szervezete, a Drogmentes Világért Alapítvány bannere látható, illetve a szócikkek alatt az "Ajánljuk még" részben további hirdetések jelennek meg.

**Comment by scripthunter7** [comment]
Szia!

Beraktam: https://github.com/hufilter/hufilter-dev/commit/37714c9d9834367e2a050db43907dc50fb19b45d

Az issue-t zárom, ha kérdésed/észrevételed van, írj nyugodtan kommentet.
