### ISSUE TITLE
csaladinet.hu

### ISSUE THREAD

**Issue by JobcenterTycoon** [hufilter/hufilter#12]
Ads on the page `https://www.csaladinet.hu/`

<img width="1143" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/174498122-aec6153d-6e62-40ce-bce4-ef96bdc99bfe.PNG">

Adblocker: uBlock Origin default + HUN: hufilter

**Comment by scripthunter7** [comment]
Cannot reproduce. For me, it works well with
- AdGuard: AdGuard Base Filter + hufilter
- uBlock Origin: uBlock filters + EasyList + hufilter

![opera_qOAJj1o95G](https://user-images.githubusercontent.com/57285466/174565050-1c3c36a3-a7b8-4d58-a51b-f502817e0849.png)

**Comment by JobcenterTycoon** [comment]
The ads got removed by the site owner
