### ISSUE TITLE
port.hu tv műsor nem tölt be

### ISSUE THREAD

**Issue by Tom1235** [hufilter/hufilter#15]
port.hu tv műsor nem tölt be (https://port.hu/tv), a többi, mozi, stream stb. jó

**Comment by scripthunter7** [comment]
@Tom1235 Milyen adblocker-t használsz és milyen filter-eket? Nekem AdGuard (Base Filter + Hufilter), uBlock (uBlock Filters + Hufilter) mellett betölt.

**Comment by scripthunter7** [comment]
@Tom1235 Elvileg most már jó lesz, néhány órán belül minden adblockerben elérhető lesz a frissítés.

**Comment by Tom1235** [comment]
Köszönöm, már jó is :)

scripthunter7 ***@***.***> ezt írta (időpont: 2022. nov. 6.,
V, 12:53):
