### ISSUE TITLE
Hiányzó gombok a Totalcar fejlécén

### ISSUE THREAD

**Issue by szalas** [hufilter/hufilter#2]
Sziasztok, A képen látható Totalcar mellett levő 2 gomb nem jelenik meg, ha a hufilter be van kapcsolva. Valószínűleg az adblock blockoló blokkoló? script miatt tűnnek el.

uBlock Origin 1.37.2
hufilter
! Version: 202108181006
! Title: hufilter

![Screenshot 2021-08-18 at 13-48-17 Totalcar](https://user-images.githubusercontent.com/13077101/129892949-4a3e9019-e132-48d6-a3fa-65bf30f9f146.png)

**Comment by scripthunter7** [comment]
@szalas Szia, nem, nem az anti-anti-adblock miatt nem jelenik meg, hanem emiatt a szabály miatt nem:
```css
totalcar.hu###bannerHeaderLink
```
Itt, ezen a `bannerHeaderLink`-en belül valószínűleg régebben valamilyen hirdetés képe jelenhetett meg, ki is van ott kommentelve valami. Maga az elem neve is "banner header", gondolom ezek miatt lett anno hozzáadva. Itt az a kódrészlet, amiről szó van:
```html
<div id="bannerHeaderLink" class="header-tk-ajanlo__tk-logo">
    <!-- tc banner módosítás --> 
    <!-- <img id="bannerImageHeader" class="lazy" src="#" /> -->
    <a class="tc-banner-btn bannerImageHeaderLeft btn-darkblue" href="http://bit.ly/totalcheck_tcheader"></a>
    <a class="tc-banner-btn bannerImageHeaderRight btn-darkblue" href="https://totalcar.hu/totalkar/?utm_medium=fejlec&amp;utm_source=totalcarhu&amp;utm_campaign=nem_szerzo&amp;utm_term=header_button_desktop_darkblue"></a>
</div>
```

Ha szeretnéd, ezt ezzel a szabállyal tudod feloldani:
```css
totalcar.hu#@##bannerHeaderLink
```

Egyébként ez inkább a self-promition szekcióba esik, sem mint az ads-be.

-----

Ami hibát viszont én találtam, ha a 2. gombra kattintasz, akkor a kártörténet lekérdezés nem jó, bekapcsolt hufilterrel nem jelenik meg semmi érdemi content, csak a háttér: https://totalcar.hu/totalkar/ 

Erről pedig ez a szabály tehet:
```css
totalcar.hu,totalbike.hu,divany.hu##body > section:not(.site-header):last-of-type
```

Itt egyelőre csak annyi a teendő, hogy ki kell egészíteni, hogy kizárja az érintett `section`-t is, és megjelenjen a form:
```css
totalcar.hu,totalbike.hu,divany.hu##body > section:not(.site-header):not(#toreskar):last-of-type
```

**Comment by szalas** [comment]
Köszi!
