### ISSUE TITLE
[NSFW] napiszex.hu

### ISSUE THREAD

**Issue by felix-22** [hufilter/hufilter#3]
LINK: `https://napiszex.hu/`
Ad-blocker: uBO 1.37.3rc3
Problem: ADS
It's a legitimate hungary porn site:
![1](https://user-images.githubusercontent.com/75935068/133978325-b4658eaf-60b0-45db-9356-07b5e4e3cfa8.png)

**Comment by scripthunter7** [comment]
Hello!

Please add following rules to your custom rule list:
```css
!annoyances
napiszex.hu##.ckwrap
!selfpromo
napiszex.hu###logo + .partner
!ads
napiszex.hu##.banner-bottom
napiszex.hu##.banner
```

If the issue still present, please send me an example link where it occurs.

**Comment by scripthunter7** [comment]
Thanks for your feedback, i'll be add these rules soon
