### ISSUE TITLE
szepsegbroker.hu/elements/bannerz

### ISSUE THREAD

**Issue by mtxadmin** [hufilter/hufilter#5]
How can I propose a rule?

||szepsegbroker.hu/elements/bannerz

**Comment by mtxadmin** [comment]
And: ctag.hu domain is closed.

**Comment by scripthunter7** [comment]
> How can I propose a rule?

You can create your PR in the dev repo: https://github.com/hufilter/hufilter-dev/pulls
This repo is release-only.
